name: Daily - Do npm install and run all unit tests

on:
  schedule:
    # run daily at midnight
    - cron: '0 0 * * *'

jobs:
  build:
    uses: adobe/aio-resuable-workflows/.github/workflows/daily.yml@main
